name: Actions

on: [push, pull_request]

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          Unity -quit -batchmode -nographics -buildTarget EmbeddedLinux -executeMethod Builder.Build -projectPath "."
        # uses: game-ci/unity-builder@v4
        # env:
        #   UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        #   UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        #   UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        # with:
        #   targetPlatform: WebGL

      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
