name: Unity WebGL Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Unity
      uses: game-ci/setup-unity@v4
      with:
        unityVersion: 2022.3.16f1
        modules: WebGL

    - name: Build WebGL
      run: |
        Unity/Editor/Unity -batchmode -quit -projectPath . -executeMethod BuildScript.BuildWebGL

    - name: Archive WebGL Build
      uses: actions/upload-artifact@v3
      with:
        name: WebGL-Build
        path: build
